config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "/orders/all", to: "orders#all_orders", as: :all_orders
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sale", to: "orders#sale", as: :sale
  get "/date_report", to: "orders#date_report", as: :date_report
  get "/search", to: "search#search", as: :search
  post "/clerk", to: "users#clerk", as: :clerk
  post "/clerk_update", to: "users#clerk_update", as: :clerk_update
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true

  def to_a_string
    "#{name} #{description} #{menu.name} #{price}"
  end
end

app/controllers/menu_item_controller.rb
class MenuItemsController < ApllicationController
  skip_before_action :verify_authenticity_token

  def index
    @menu_id = params[:menu_id]
    @menu_items = MenuItem.return(@menu_id)
    @menu_name = Menu.find(@menu_id).menu_name
  end

  def create
    MenuItem.create!(
      name: params[:name],
      description: params[:description],
      price: params[:price],
      menu_id: params[:menu_id],
    )
    redirect_to menu_items_path(menu_id: params[:menu_id])
  end

  def destroy
    id = params[:id]
    menu_item = MenuItem.find(id)
    menu_item.destroy
    redirect_to menu_items_path(menu_id: params[:menu_id])
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
  end

  def show
  end

  def create
    if params[:id]
      menu = params[:id] == "Add a Menu" ? Menu.new(name: params[:new_menu_name]) : Menu.find(params[:id])
      menu.save
      menu_item = MenuItem.new(name: params[:name].capitalize, description: params[:description].capitalize, menu_id: menu.id, price: params[:price])
      if menu.save && menu_item.save
        flash[:notice] = "Item added"
      else
        flash[:error] = menu_item.errors.full_messages + menu.errors.full_messages
      end
    else
      flash[:alert] = "Select a Menu Name"
    end
    redirect_to menus_path
  end

  def edit
    ensure_owner_logged_in
    @menu_item = MenuItem.find(params[:id])
  end

  def destroy
    ensure_owner_logged_in
    menu_item = MenuItem.find(params[:id])
    menu = Menu.find(menu_item.menu_id)
    if menu.menu_items.count == 1
      menu.destroy
    end
    menu_item.destroy
    flash[:alert] = "Item Deleted"
    redirect_to menus_path
  end

  def update
    menu_item = MenuItem.find(params[:id])
    menu_item.name = params[:name].capitalize
    menu_item.description = params[:description].capitalize
    menu_item.price = params[:price]
    if menu_item.save
      flash[:notice] = "Item Updated successfully!"
      redirect_to menus_path
    else
      flash[:error] = menu_item.errors.full_messages.join(", ")
      redirect_to edit_menu_item_path
    end
  end

  private

  def permit_params
    params.require(:menu_item).pemit(:name, :description, :menu_name, :price)
  end
end

app/views/menu_items/_menuItems-list.html.erb
<div class="MenuItems">
  <% @menus.each do |menu| %>
    <ul class="MenuItems-List">
      <h3 class="MenuName" id=<%= menu.name %>>
        <%= menu.name %>
      </h3>
      <% menu.menu_items.order(:name).each do |menu_item| %>
        <li class="MenuItem">
          <p>
            <%= menu_item.name %>
            <span class="MenuItem-rating">
              <% menu_item.ratings.to_i.times do %>
              <% end %>
              <% (5 - menu_item.ratings.to_i).times do %>
              <% end %>
            </span>
            <span class="MenuItem-details">
              <span class="MenuItem-price">
                ₹<%= menu_item.price %>
              </span>
              <span class="MenuItem-description"> <%= menu_item.description %> </span>
            </span>
          </p>
          <p class="UpdateItem">
          <% if @current_user.is_owner? %>
              <p class="MenuItem-delete">
                <%= link_to edit_menu_item_path(id: menu_item.id) do %>

                <% end %>
                <%= link_to menu_item, method: :delete, data: { confirm: "Are you sure?" } do %>
                  <%= image_tag "trash-can-outline.png" %>
                <% end %>
              </p>
            <% end %>
            <p class="OrderItem-add">
            <% if @order %>
              <% if @order.order_items.get_order_item(menu_item.id).exists? %>
                <%= link_to "-", order_item_path(id: @order.order_item(menu_item.name).id),
                            { :method => :delete } %>
                <%= @order.order_items.get_order_item(menu_item.id).count %>
                <%= link_to "+", order_items_path(menu_item_id: menu_item.id),
                            { :method => :post } %>
              <% else %>
                <%= link_to "Add +", order_items_path(menu_item_id: menu_item.id),
                            { :method => :post } %>
              <% end %>
            <% else %>
              <%= link_to "Add +",order_items_path(menu_item_id: menu_item.id),
                          { :method => :post } %>
            <% end %>
          </p>
          </p>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/menu_items/_menulist.html.erb
<div class="MenuItems">
  <% @menus.each do |menu| %>
    <ul class="MenuItems-List">
      <h3 class="MenuName" id=<%= menu.name %> >
        <%= menu.name %>
      </h3>
      <% menu.menu_items.order(:name).each do |menu_item| %>
        <li class="MenuItem">
          <p class="MenuItem-Name">
            <%= menu_item.name %>
            <span class="MenuItem-rating">
              <% menu_item.ratings.to_i.times do %>
               <%= image_tag "rate.png" %>
              <% end %>
              <% (5 - menu_item.ratings.to_i).times do %>
               <%= image_tag "star1.png" %>
              <% end %>
            </span>
            <span class="MenuItem-details">
              <span class="MenuItem-price"> Rs. <%= menu_item.price %> </span>
              <span class="MenuItem-description"> <%= menu_item.description %> </span>
            </span>
          </p>
          <p class="UpdateItem">
            <% if @current_user.is_owner? %>
              <p class="MenuItem-delete">
                <%= link_to edit_menu_item_path(id: menu_item.id) do %>
                  <%= image_tag "edit1.png" %>
                <% end %>
                <%= link_to menu_item, method: :delete, data: { confirm: "Are you sure?" } do %>
                  <%= image_tag "trash-can-outline.svg" %>
                <% end %>
              </p>
            <% end %>
            <p class="OrderItem-add" >
             <% if @order %>
              <% if @order.order_items.get_order_item(menu_item.id).exists? %>
               <p class="AddToCart">
                <%= link_to "-", order_item_path(id: @order.order_item(menu_item.name).id),
                            { :method => :delete } %>
               </p>
               <p class="OrderedQuantity">
                <%= @order.order_items.get_order_item(menu_item.id).count %>
               </p>
                <%= link_to "+", order_items_path(menu_item_id: menu_item.id),
                            { :method => :post } %>
              <% else %>
               <p class="AddToCart">
                <%= link_to "Add", order_items_path(menu_item_id: menu_item.id),
                            { :method => :post } %>
               </p>
              <% end %>
            <% else %>
              <%= link_to "Add", order_items_path(menu_item_id: menu_item.id),
                          { :method => :post } %>
            <% end %>
          </p>
          <% if @current_user.is_owner? %>
            <p class="MenuItemDelete">
             <%= link_to edit_menu_item_path(id: menu_item.id) do %>
               <%= image_tag "edit1.png", class: "Delete" %>
             <% end %>
             <%= link_to menu_item, method: :delete do %>
              <% image_tag "trash-can-outline.svg" %>
             <% end %>
            </p>
          <% end %>
          </p>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/menu_items/edit.html.erb
<main class="EditPage">
  <p class="EditPage-header">
    Edit Item
  </p>
  <%= form_with url: menu_item_path, method: :patch, class: "Update-form" do |form| %>
   <p class="EditItem-header">
   Item Name :
   </p>
    <%= form.text_field :name,
                        placeholder: "Item Name",
                        value: @menu_item.name,
                        autofocus: "autofocus" %>
    <br>
    <p class="EditItem-header">
    Price :
    </p>
    <%= form.number_field :price,
                          placeholder: "Price",
                          value: @menu_item.price,
                          class: "edit-item-price" %>
    <br>
    <p class="EditItem-header">
    Description :
    </p>
    <%= form.text_field :description,
                        value: @menu_item.description,
                        placeholder: "Description" %>
    <br>
    <%= form.submit "Update", class: "Update-button" %>
  <% end %>
</main>