config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "/orders/all", to: "orders#all_orders", as: :all_orders
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sale", to: "orders#sale", as: :sale
  get "/date_report", to: "orders#date_report", as: :date_report
  get "/search", to: "search#search", as: :search
  post "/clerk", to: "users#clerk", as: :clerk
  post "/clerk_update", to: "users#clerk_update", as: :clerk_update
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true
  has_many :orders

  def is_clerk?
    clerk = role == "clerk" ? true : false
  end

  def is_owner?
    owner = role == "owner" ? true : false
  end

  def self.clerks
    User.all.where("role = ?", "clerk")
  end

  def self.owners
    User.all.where("role = ?", "owner")
  end

  def self.customers
    User.all.where("role = ?", "customer")
  end

  def self.get_user_by_email(email)
    user = all.where("email = ?", email).exists? ? find_by(email: email) : false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in, only: [:create, :new]

  def new
    if current_user
      flash[:notice] = "Signed In"
      redirect_to menus_path
    else
      render "users/new"
    end
  end

  def show
    unless current_user
      redirect_to root_path
    end
  end

  def index
    ensure_owner_logged_in
    @users = User.all
    @clerks = User.clerks.order(:id)
    @customers = User.customers.order(:id)
  end

  def create
    name = params[:name]
    email = params[:email]
    password = params[:password]
    user = User.new(name: name.capitalize, email: email, role: "customer", password: password)
    if user.save
      user.save!
      session[:current_user_id] = user.id
      redirect_to new_session_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def edit
    unless current_user
      redirect_to root_path
    end
  end

  def clerk
    ensure_owner_logged_in
    name = params[:name]
    email = params[:email]
    password = params[:password]
    user = User.new(name: name.capitalize, email: email, role: "clerk", password: password)
    if user.save
      user.save!
      redirect_to request.referer
      flash[:notice] = "Clerk Account Added"
    else
      flash[:error] = user.errors.full_messages
      redirect_to request.referer
    end
  end

  def clerk_update
    ensure_owner_logged_in
    id = params[:id]
    user = User.find(id)
    if user.is_clerk?
      user.destroy
      flash[:notice] = "Clerk Account deleted"
    else
      flash[:alert] = "Role can't be changed"
    end
    redirect_to request.referer
  end
end

app/views/users/_user-details.html.erb
<h3>
  <th colspan="5" class="table-header"><%= heading %></th>
</h3>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Email</th>
  <th>Orders</th>
</tr>
<% if owner %>
  <tr class="user-row" id=<%= owner.id %>>
    <td><%= owner.id %></td>
    <td><%= owner.name %></td>
    <td><%= owner.email %></td>
    <td>
      <% owner.orders.delivered.ids.each do |id| %>
        <%= link_to id, "orders/all##{id}" %>,
      <% end %>
    </td>
  </tr>
<% elsif roles %>
  <% roles.each do |role| %>
    <tr class="user-row" id=<%= role.id %>>
      <td><%= role.id %></td>
      <td><%= role.name %></td>
      <td><%= role.email %></td>
      <td>
        <% role.orders.delivered.ids.each do |id| %>
          <%= link_to id, "orders/all##{id}" %>,
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/users/_users.html.erb
<h3>
  <th colspan="5" class="Table-Header"><%= heading %></th>
</h3>
<tr>
  <th>User Id</th>
  <th>Name</th>
  <th>Email</th>
  <th>Orders</th>
  <th> Edit</th>
</tr>
<% if owner %>
  <tr class="User-Data" id=<%= owner.id %>>
    <td><%= owner.id %></td>
    <td><%= owner.name %></td>
    <td><%= owner.email %></td>
    <td>
       <% owner.orders.delivered.ids.each do |id| %>
        <%= link_to id, "orders/#{id}" %>,
       <% end %>
    </td>
    <td>Nothing</td>
  </tr>
<% elsif roles %>
  <% roles.each do |role| %>
    <tr class="User-Data" id=<%= role.id %>>
      <td><%= role.id %></td>
      <td><%= role.name %></td>
      <td><%= role.email %></td>
      <td>
         <% role.orders.delivered.ids.each do |id| %>
           <%= link_to id, "orders/#{id}" %>,
         <% end %>
      </td>
      <% if heading == "Clerks" %>
        <td>
           <%= image_tag "trash-can-outline.svg" %>
           <%= link_to "delete", clerk_update_path(id: role.id), :method => :post %>
        </td>
      <% else %>
          <td>
            Nothing
          </td>
      <% end %>
    </tr>
  <% end %>
<% end %>

app/views/users/index.html.erb
<main class="Users-Main">
  <section>
    <table class="Clerks">
      <%= render partial: "users", locals: { roles: nil, owner: @current_user, heading: "Owner" } %>
      <%= render partial: "users", locals: { roles: @clerks, owner: nil, heading: "Clerks" } %>
      <%= render partial: "users", locals: { roles: @customers, owner: nil, heading: "Customers" } %>
    </table>
  </section>
  <div class="Add-Clerk">
    <h2 class="Signup-Clerk">Add Clerk </h2>
   <%= form_with url: clerk_path, class: "SignUp-Form" do |form| %>
    <div>
     <%= form.text_field :name,
                         placeholder: "Name",
                         autofocus: true %>
    </div>
    <br>
     <%= form.email_field :email,
                          placeholder: "Email" %>
    <br>
     <%= form.password_field :password,
                             placeholder: "Password" %>
    <br>
    <%= form.submit "Join", data: { "disable-with": "Appointing" }, class: "SignUp-Button" %>
   <% end %>
  </div>
</main>

app/views/users/new.html.erb
<body>
<main class="SignUpMain">
  <h2 class="Signup-Header">Ready to Sign Up :) </h2>
 <section>
  <%= form_with url: users_path, class: "SignUp-Form" do |form| %>
    <div>
    <%= form.text_field :name,
                        placeholder: "Name", autofocus: true %>
    </div>
    <br>
    <%= form.email_field :email,
                         placeholder: "Email" %>
    <br>
    <%= form.password_field :password,
                            placeholder: "Password" %>
    <br>
    <%= form.text_field :role, value: "customer", readonly: true %>
    <br>
    <%= form.submit "Sign up", data: { "disable-with": "Entering" }, class: "SignUp-Button" %>
    <p class="SignUp-Login">
      Already an user?
      <%= link_to "Login here", new_session_path, class: "Login-Page" %>
    </p>
  <% end %>
 </section>
</main>
</body>

app/views/users/show.html.erb
<div class="Profile-Main">
 <div class="Profile-Image">
  <%= image_tag "user.png" %>
 </div>
 <div class="Welcome-mesg">
   Welcome  <%= @current_user.name %>
 </div>
 <div class="Details-Block">
  <div class="Details">
   User Id : <%= @current_user.id %>
  </div>
  <div class="Details">
   Name : <%= @current_user.name %>
  </div>
  <div class="Details">
   Email : <%= @current_user.email %>
  </div>
  <div class="Details">
   Orders : <%= @current_user.orders.count %>
  </div>
  <div class="Details">
   Role : <%= @current_user.role %>
  </div>
 </div>
</div>