config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "/orders/all", to: "orders#all_orders", as: :all_orders
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sale", to: "orders#sale", as: :sale
  get "/date_report", to: "orders#date_report", as: :date_report
  get "/search", to: "search#search", as: :search
  post "/clerk", to: "users#clerk", as: :clerk
  post "/clerk_update", to: "users#clerk_update", as: :clerk_update
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :user
  validates :address, presence: true

  def to_a_string
    "#{id} #{date} Items:#{order_items.map { |item| item.menu_item_name }.join("---")} TOTAL PRICE:#{total_price} STATUS:#{status} #{delivered_at}"
  end

  def self.delivered
    where.not("status = ? ", "being_created")
  end

  def self.pending_orders
    where("status= ?", "order_confirmed")
  end

  def self.finished
    where("status=?", "order_completed")
  end

  def self.being_created
    where("status= ?", "being_created").first
  end

  def to_a_string
    "#{id} #{order_id} #{menu_item_id} #{menu_item_name} #{menu_item_price}"
  end

  def order_item(menu_item_name)
    order_items.where(menu_item_name: menu_item_name).first
  end

  def get_number_of_items(order_item)
    order_items.where(id: order_item.id).count
  end

  def all_menu_item_names
    order_items.order(:menu_item_name).map { |item| item.menu_item_name }
  end

  def self.get_order_by_id(id)
    order = all.where("id = ?", id).exists? ? find(id) : false
  end

  def walkin_order?
    user = User.find(user_id)
    if user.is_owner? || user.is_clerk?
      true
    else
      false
    end
  end

  def self.completed
    where("status = ? ", "order_delivered")
  end

  def self.destroy_wrong_items(id)
    all.each do |order|
      order.order_items.all.each do |order_item|
        if order_item.menu_item_id == id
          order_item.destroy
        end
      end
    end
  end

  def self.get_purchased_items
    items = []
    all.delivered.each do |order|
      items += order.all_menu_item_names
    end
    items
  end

  def self.final_sales(menu_item_name)
    price = 0
    all.delivered.each do |order|
      order.order_items.all.each do |order_item|
        if order_item.menu_item_name == menu_item_name
          price = price + order_item.menu_item_price
        end
      end
    end
    price
  end

  def self.get_datewise_orders(begin_date, end_date)
    all.where("date >= ? and  date<= ?", begin_date, end_date)
  end

  def order_status
    if status == "being_created"
      "Being Created"
    elsif status == "order_confirmed"
      "order confirmed"
    else
      "Delivered at #{delivered_at.strftime("%d %B,%Y - %I:%M %p")}"
    end
  end

  def total_price
    price = 0
    order_items.each { |item| price = price + item.menu_item_price }
    price
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = @current_user.orders.order(:id)
  end

  def pending_orders
    ensure_owner_or_clerk_logged_in
    orders = Order.order(:id).pending_orders
  end

  def show
    @order = Order.find(params[:id])
    @user = User.find(@order.user_id)
    if @user.id == current_user.id
    else
      ensure_owner_logged_in
    end
  end

  def create
    order = current_user.orders.being_created
    if order.order_items.empty?
      redirect_to(cart_path, alert: "Order should have atleast 1 fooditem")
    else
      order.status = "order_confirmed"
      order.address = params[:address]
      order.ordered_at = DateTime.now
      if order.save
        flash[:notice] = "Order accepted.Soon your order will be delivered"
        redirect_to orders_path
      else
        flash[:error] = order.errors.full_messages
        redirect_to cart_path
      end
    end
  end

  def sale
    ensure_owner_logged_in
    @users = User.all
    @orders = Order.completed
    @menus = Menu.all
    @menu_items = MenuItem.all
  end

  def update
    ensure_owner_or_clerk_logged_in
    order = Order.find(params[:id])
    order.status = "Order_delivered"
    order.delivered_at = Time.now + 19800
    order.date = Date.today
    order.save!
    flash[:notice] = "#{order.id} is delivered!"
    redirect_to "/pending_orders"
  end

  def cart
    @order = current_user.orders.being_created
  end

  def all_orders
    ensure_owner_logged_in
    @all_orders = Order.order(id: :desc)
  end

  def date_report
    @begin_date = params[:begin_date]
    @end_date = params[:end_date]
    @users = User.all
    @orders = Order.delivered.get_datewise_orders(@begin_date, @end_date)
    @menus = Menu.all
    @menu_items = MenuItem.all
  end

  def destroy
    order = Order.find(params[:id])
    if order.user_id == current_user.id
      order.destroy
      flash[:notice] = "Order deleted"
    else
      flash[:alert] = "You are not permitted"
    end
    redirect_to request.referer
  end

  def rating
    order = Order.find(params[:id])
    order.ratings = params[:rating]
    order.save!
    order.order_items.rate_menu_items(params[:rating])
    flash[:notice] = "Thanks for rating"
    redirect_to request.referer
  end
end

app/views/orders/_final.html.erb
<table class="Clerks">
  <h3>
    <th colspan="4" class="Header-table"><%= heading %></th>
  </h3>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Total Orders</th>
    <th>Orders</th>
  </tr>
  <% roles.each do |role| %>
    <% if role.orders.delivered.get_datewise_orders(@begin_date, @end_date) %>
      <tr>
        <td>
         <%= role.id %>
        </td>
        <td>
         <%= role.name %>
        </td>
        <td>
         <%= role.orders.delivered.get_datewise_orders(@begin_date, @end_date).count %>
        </td>

        <td>
           <% role.orders.delivered.get_datewise_orders(@begin_date, @end_date).ids.each do |id| %>
              <%= link_to id, "orders/#{id}" %>,
           <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/orders/_orders.html.erb
<% orders.each do |order| %>
  <div class="Orderone" id="<%= order.id %>">
      <div class ="Order-section">
        <p class="Order-sub">Order Id</p>
        <div class="Order-id"><%= order.id %></div>
      </div>

      <div class="Order-section">
        <p class="Order-sub">Details</p>

        <% if order.user.is_clerk? || order.user.is_owner? %>
        <div class="Walk-image">
          Walk In Customer 
        </div>
        <% else %>
          <div class="User-name">
            <%= order.user.name.capitalize %>
          </div>
        <% end %>

        <% if order.date %>
          <div class="Order-date">
            <%= order.ordered_at.strftime("%d %B,%Y - %I:%M %p") %>
          </div>
        <% end %>
      </div>

      <span class="Order-Status"
            <% if order.delivered_at %>
              style="color:blue;font-weight:bold"
            <% elsif order.ordered_at %>
              style="color:red;font-weight:bold"
            <% else %>
              style="color:green;font-weight:bold"
            <% end %> >
            <p class="Status-sub">Status</p>
            <div class="Status-main">
             <%= order.order_status %>
            </div>
      </span>
      
      <div class="Order-section">
        <p class="Order-sub">Rating</p>
        <div class="Order-ratings">
          <%= render partial: "ratings", locals: { order: order, mark_as_delivered: mark_as_delivered } %>
        </div>
      </div>

      <section class="Order-section" id="Order-details">
          <div class="Order-sub"> Orders</div>
         <div class="Order-calculation" >
           <% order.all_menu_item_names.uniq.each do |menu_item| %>
                <%= menu_item %> x <%= order.all_menu_item_names.count(menu_item).to_s %>=
                Rs.<%= order.order_items.get_menu_item_price(menu_item) * order.all_menu_item_names.count(menu_item) %>
           <% end %>
         </div>
      </section>

      <div class="Order-section">
        <p class="Order-sub">Price</p>
        <div class="Order-price">Rs.<%= order.total_price %></div>
      </div>

      <div class="Order-section">
        <div class="Order-Invoice">
         <% if order.status == "order_delivered" %>
           <%= image_tag "invoice.png" %>
             <%= link_to "Invoice", order_path(id: order.id) %>
         <% elsif order.user_id == @current_user.id %>
           <%= image_tag "trash-can-outline.svg" %>
           <%= link_to "Del", order_path(id: order.id), :method => :delete %>
          <% else %>

          <% end %>
        </div>
      </div>
  </div>
<% end %>

app/views/orders/_rating.html.erb
<p class="Rating">
  <% if mark_as_delivered %>
    <%= link_to "Mark as Delivered", order_path(order.id), method: "patch" %>
  <% elsif order.delivered_at.nil? %>
    Order is under process
  <% else %>
    <% if order.ratings == 0 && order.user == @current_user %>
      <% 5.times do |img| %>
        <%= link_to order_rating_path(id: order.id, rating: img + 1), method: :put, class: "Rating-Stars" do %>
          <%= image_tag "star1.png", id: img + 1 %>
        <% end %>
      <% end %>
    <% else %>
      <% order.ratings.times do %>
        <%= image_tag "rate.png" %>
      <% end %>
      <% (5 - order.ratings).times do %>
        <%= image_tag "star1.png" %>
      <% end %>
    <% end %>
  <% end %>
</p>

app/views/orders/_ratings.html.erb
<p class="Rating">
  <% if mark_as_delivered %>
    <%= link_to "Deliver Order", order_path(order.id), method: "patch" %>
  <% elsif order.delivered_at.nil? %>
    Rate after order confirmation
  <% else %>
    <% if order.ratings == 0 && order.user == @current_user %>
      <% 5.times do |img| %>
        <%= link_to order_rating_path(id: order.id, rating: img + 1), method: :put, class: "Rating-Stars" do %>
          <%= image_tag "star1.png", id: img + 1 %>
        <% end %>
      <% end %>
    <% else %>
      <% order.ratings.times do %>
        <%= image_tag "rate.png" %>
      <% end %>
      <% (5 - order.ratings).times do %>
        <%= image_tag "star1.png" %>
      <% end %>
    <% end %>
  <% end %>
</p>

app/views/orders/all_orders.html.erb
<div class="Orders">
  <h3 class="Orders-title">Full Orders</h3>
  <%= render partial: "orders", locals: { orders: Order.order(id: :desc).delivered, mark_as_delivered: false } %>
</div>

app/views/orders/cart.html.erb
<div class="Cart">
  <h3 class="Cart-Heading">Cart</h3>
  <% if @order %>
    <% if @order.order_items.empty? %>
      <h2 class="empty-cart">Cart is empty</h2>
    <% else %>
      <div class="Cart-item-price">
        <ul>
        <div class="Cart-Items">
          <% @order.all_menu_item_names.uniq.each do |menu_item_name| %>
            <li class="Cart-item" >
              <div class="Cart-Item-Name">Item :<%= menu_item_name %></div>
              <div class="CartItem-quantity">
                  Quantity =
                <p class="CartItem-add">
                  <%= link_to "-",
                              order_item_path(id: @order.order_item(menu_item_name).id, cart: 1),
                              { :method => :delete } %>
                  <%= @order.all_menu_item_names.count(menu_item_name) %>
                  <%= link_to "+",
                              order_items_path(menu_item_id: @order.order_item(menu_item_name).menu_item_id, cart: 1),
                              { :method => :post } %>
                      
                </p>
                <div class="qty">
                  Rs <%= @order.order_items.get_menu_item_price(menu_item_name) * @order.all_menu_item_names.count(menu_item_name) %>
                </div>
              </div>
            </li>
          <% end %>
        </div>
        </ul>
        <p class="Cart-total-price" >
          <div class="total-price"> Total Price : Rs. <%= @order.total_price %></div>
        </p>
        <%= form_with(model: @order, url: orders_path, method: "post", local: true) do |form| %>
          <h2 class="Address-Header">Address</h2>
          <div>
           <%= text_area_tag "address", nil, rows: 5, cols: 30, class: "Cart-Address" %>
          </div>
          <%= form.submit "Order", data: { "disable-with": "Ordering" }, class: "cart-checkout" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h2 class="empty-cart">Cart is empty</h2>
  <% end %>
</div>

app/views/orders/date_report.html.erb
<h3 class="Report-Heading">Sales Between <%= @begin_date %> and <%= @end_date %></h3>
<div class="Report-page">
    <div class="User-analysis">
      <div class ="Sub-analysis"><%= render partial: "final", locals: { roles: @users.owners, heading: "Owners" } %></div>
      <div class ="Sub-analysis"><%= render partial: "final", locals: { roles: @users.clerks, heading: "Clerks" } %></div>
      <div class ="Sub-analysis"><%= render partial: "final", locals: { roles: @users.customers, heading: "Customers" } %></div>
    </div>
    <% price = 0 %>
    <% count = 0 %>
    <% @orders.each { |order| price = price + order.total_price } %>
    <% price_offline = 0 %>
    <% @orders.all.each do |order| %>
        <% if order.walkin_order? %>
          <% price_offline = price_offline + order.total_price %>
          <% count = count + 1 %>
        <% end %>
    <% end %>

    <div class="Sales-detail">
     <div class ="Sales-Title">Vended Items</div>
     <div class="Itemwise-sales">
       <% items = @orders.get_purchased_items %>
       <% items.uniq.each do |menu_item| %>
        <div class="Itemwise-analysis"> <%= menu_item %> x <%= items.count(menu_item) %> = <%= @orders.final_sales(menu_item) %></div>
       <% end %>
     </div>
     <div class="Item-analysis">
       <div class ="Report-info">Online Orders : <%= @orders.count - count %></div>
       <div class ="Report-info">Offline Orders : <%= count %></div>
       <div class ="Report-Total-info">Total Orders : <%= @orders.count %></div>
       <h3 class = "Report-info">Online sales : Rs.<%= (price - price_offline) %>
       <h3 class = "Report-info">Offline sales : Rs.<%= price_offline %></h3>
       <h3 class = "Report-Total-info">Total sales : Rs.<%= price %></h3>
     </div>
    </div>
</div>

app/views/orders/index.html.erb
<div class="Orders">
  <h3 class="Orders-title">
   Your Orders
  </h3>
  <%= render partial: "orders", locals: { orders: @orders, mark_as_delivered: false } %>
</div>

app/views/orders/pending_orders.html.erb
<div class="Orders">
  <h3 class="Orders-title">
   Pending Orders
  </h3>
  <%= render partial: "orders", locals: { orders: Order.order(:id).pending_orders, mark_as_delivered: true } %>
</div>

app/views/orders/sale.html.erb
<h2 class="Sales-Main">Data</h2>
<div class="Sales-Report">
 <h3 class="Sale-Menu">
  Total Menus : <%= @menus.count %>
 </h3>
 <h3 class="Sale-Menu">
  Total Items : <%= @menu_items.count %>
 </h3>
 <h3 class="Sale-Menu">
  Total Clerks : <%= @users.clerks.count %>
 </h3>
 <h3 class="Sale-Menu">
  Total Buyers : <%= @users.customers.count %>
 </h3>

 <% price = 0 %>
 <% @orders.each { |order| price = price + order.total_price } %>
  <div class = "SalesDivision">
   <div class="Sub-head">Date Wise Report </div>
    <%= form_tag("/date_report", method: "get") do %>
      <%= date_field_tag "begin_date", nil, class: "Date-field", required: true %>
      <%= date_field_tag "end_date", nil, class: "Date-field", required: true %>
      <div><%= submit_tag nil, class: "Submit-button", value: "Display Report" %></div>
    <% end %>
   </div>
  </div>

app/views/orders/show.html.erb
<div class="Invoice-division">
  <h2 class="Invoice-Header">PK-PLAZA</h2>
  <h2 class="InvoiceTitle">Invoice No: <%= @order.id %> </h2>
  <div class="Invoice-div">
    <div class="Detail-div">
      <span class="Invoice-User">
          <h3 class="Invoice-subheading">Buyer Details</h3>
          <p class="Detail">User id : <%= @order.user.id %> </p>
          <p class="Detail">Name : <%= @user.name %></p>
          <p class="Detail">Email : <%= @user.email %></p>
          <% if @user.is_owner? || @user.is_clerk? %>
            <p class="Detail">Walk In Customer <%= image_tag "buyer.png" %></p>
          <% else %>
            <p class="Detail">Online customer </p>
          <% end %>
      </span>
      <span class="Invoice-Order">
          <h3 class="Invoice-subheading">Order Details</h3>
          <p class="Detail">Order Id : <%= @order.id %></p>
          <p class="Detail">Address : <%= @order.address %></p>
          <p class="Detail">Ordered Time : <%= @order.ordered_at.strftime("%d %B,%Y - %I:%M %p") %></p>
      </span>
    </div>
    <table class="Invoice-Table">
      <tr>
      <th>ITEM</th>
      <th>QUANTITY</th>
      <th>AMOUNT</th>
      </tr>
      <% @order.all_menu_item_names.uniq.each do |menu_item| %>
        <tr>
          <td><%= menu_item %></td>
          <td><%= @order.all_menu_item_names.count(menu_item).to_s %></td>
          <td><%= @order.order_items.get_menu_item_price(menu_item) * @order.all_menu_item_names.count(menu_item) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="InvoiceFinal">
     <div class="Invoice-message">Thank You<br>Visit Again:)</div>
     <div class="Invoice-Total">Total : Rs.<%= @order.total_price %></div>
  </div>
</div>