config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "/orders/all", to: "orders#all_orders", as: :all_orders
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sale", to: "orders#sale", as: :sale
  get "/date_report", to: "orders#date_report", as: :date_report
  get "/search", to: "search#search", as: :search
  post "/clerk", to: "users#clerk", as: :clerk
  post "/clerk_update", to: "users#clerk_update", as: :clerk_update
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <script>
    function display_form(val) {
      var element = document.getElementById("new_menu_name");
      if (val == "Add a Menu")
         { element.style.display = "inline"; }
      else { element.style.display = "none"; }
    }
  </script>
  </head>
  
 <body>
  <div class="head-page">
    <nav class="navbar">
    <div class="navbar-logo">
      <h2 class="navbarHeader">
       <%= image_tag "chef.png" %>
       WELCOME TO PK-PLAZA 
       </h2>
      <%= image_tag "image.png" %>
    </div>
    <div class="Buttons-container">
        <div class="navbar-indexbutton">
            <h3><%= image_tag "nav-buttons.png" %> <% if @current_user %> <%= @current_user.name %>
                                                  <% else %>
                                                    User
                                                  <% end %>
            </h3>
        </div>
      <ul class="navbarButtons">
        <% if @current_user %>
          <li class="navbarButton">
           <%= image_tag "main.png" %>
            <%= link_to "Home", menus_path %>
          </li>
          <li class="navbarButton">
           <%= image_tag "account.png" %>
           <%= link_to "Profile", user_path(id: @current_user.id) %>
          </li>
          <% if @current_user.is_owner? || @current_user.is_clerk? %>
            <li class="navbarButton">
              <%= image_tag "leftorders.png" %>
              <%= link_to "Pending Orders", pending_orders_path %>
            </li>
          <% end %>
          <% if @current_user.is_owner? %>
            <li class="navbarButton">
              <%= image_tag "List.png" %>
              <%= link_to "Full Orders", all_orders_path %>
            </li>
            <li class="navbarButton">
                <%= image_tag "price.png" %>
                <%= link_to "Details", sale_path %>
            </li>
            <li class="navbarButton">
            <%= image_tag "user1.png" %>
               <%= link_to "Users", users_path %>
            </li>
            <% end %>
            <li class="navbarButton">
              <%= image_tag "order.png" %>
              <%= link_to "Orders", orders_path %>
            </li>
            <li class="navbarButton">
              <%= image_tag "cart.png" %>
              <%= link_to "Cart", cart_path %>
            </li>
            <li class="navbarButton">
              <%= image_tag "logout.png" %>
              <%= link_to "LogOut", destroy_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="navbarButton">
              <%= image_tag "Login.png" %>
              <%= link_to "Log In", new_session_path %>
            </li>
            <li class="navbarButton">
              <%= image_tag "signup.png" %>
              <%= link_to "Sign Up", new_user_path %>
            </li>
          <% end %>
        </ul>
      </nav>
      <div class="SearchItem">
      <h3 class="OrderOnline-head">Order Online</h3>
        <div class="OnlineOrder"> <%= image_tag "onlineorder.png" %> </div>
        <%= yield :head %>
        <%= yield :search %>
      </div>
       <% if flash.alert %>
        <p class="alert"><%= alert %></p>
       <% end %>
       <% if flash[:error] %>
         <div id="error_string">
           <h2><%= flash[:error] %></h2>
         </div>
       <% end %>
       <div class="Notice">
        <% if flash.notice %>
         <p>
           <%= notice %>
         </p>
        <% end %>
       </div> 
  </div>
       <%= yield %>
       
 </body>
</html>